# .streamlit/secrets.toml

[mongo]
host = "localhost"
port = 27017


[connections.snowflake]
account = "YELBYGL-ZD54853"
user = "nguk32909"
password="Yongnguk11760."
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "PETS"
schema = "PUBLIC"